### ISSUE TITLE
composer support!

### ISSUE THREAD

**Issue by callmez** [beecloud/beecloud-php#11]

**Comment by quietbamboo** [comment]
Thanks for the suggestion, will do!

**Comment by Danzeer** [comment]
well,well....composer needs namespace! and need PHP5.3+. It seems we have to maintain both a branch for composer and the other one for none-namespace!

**Comment by Danzeer** [comment]
the other way -- keeping two sdk on same branch. 

TODO:

**Comment by Danzeer** [comment]
little busy， may finish this weekend

**Comment by Danzeer** [comment]
finish v2.2.0
