### ISSUE TITLE
bill接口channel，refund接口channel ，webhook channelType不统一

### ISSUE THREAD

**Issue by Brave-Cheng** [beecloud/beecloud-php#18]
支付接口需要以下参数：

![image](https://cloud.githubusercontent.com/assets/1323776/10385128/628d4d82-6e77-11e5-9fa7-f3b62d7faea4.png)

但是，异步回调接口的渠道参数却只有以下几类：

![image](https://cloud.githubusercontent.com/assets/1323776/10385158/b53c34d0-6e77-11e5-9a9f-c128600d144f.png)

而退款代码中也只有以下几类：

![image](https://cloud.githubusercontent.com/assets/1323776/10385161/ccc24b4e-6e77-11e5-8094-712211a1c6c7.png)

问题来了：

当仅仅使用APP发起ALI_APP支付方式时，退款如何解决？

**Comment by Danzeer** [comment]
channel 对应 channelType(只有大渠道)，app上直接发起的退款请使用预退款功能 或者使用服务器sdk实现你的退款流程

**Comment by quietbamboo** [comment]
这个问题我们需要仔细研究下，如果是我们的设计漏洞，我们会改进

**Comment by Brave-Cheng** [comment]
跟你们的开发者交流后，他的反馈是：退款传入了ALI和billNo, 你们就自己确定了到底是ALI_APP还是ALI_WEB还是其他等。 这样理解有些不太符合逻辑吧。

如果，我们APP支付传入的渠道是ALI_APP，退款我们直接传了ALI， 而对应的ALI可能是ALI_APP，ALI_WEB等等，理解上会存在异议

**Comment by Brave-Cheng** [comment]
按照你们现在的处理方式， 我们的数据库设计要保存两个渠道【ALI-用于退款时，我们传入该参数】【ALI_APP-用于知道我们是用的支付宝的哪种方式支付的】。这样是不是有些不合理？

**Comment by Danzeer** [comment]
虽然 billNo唯一，但是refund接口只有大的渠道类型， 这样会导致开发者在退款时需要通过bill发起时的订单的 渠道channel 得到 退款时的 渠道退款channel

开发者只有俩种做法：
1. 字符串分割 得到 主渠道类型（比如ALI）， 如果我们做不到规则统一，那么就不是通用方法，代码维护上讲也属于魔术了
2. 数据库订单里 存俩个字段 一个是bill的channel， 一个是refund的channel，对应的操作取对应的channel

webhook 中 由于 billNo 唯一实际 按照billNo查询到的必然是一个唯一支付的订单
但是 由于bill中是传ALI_xxx类似的子渠道，webhook中通知的又只是主渠道类型（ALI），比较难以接受

可以接受的方式：
0. 不更改， 解释这种做法
1. webhook 传递的 channelType 对应 bill中传入的channel，但是目前已有用户使用样例webhook处理方式了
2. webhook 传递 subChannelType对应 bill中传入的channel

**Comment by Danzeer** [comment]
@josephgao

**Comment by Danzeer** [comment]
webhook和 rest api 最好能统一一下

**Comment by Brave-Cheng** [comment]
@Danzeer ，支持

> webhook和 rest api 最好能统一一下

**Comment by josephgao** [comment]
webhook添加sub_channel_type字段，与支付时传入的channel相同。
