### ISSUE TITLE
弱弱地问一句

### ISSUE THREAD

**Issue by shrekmaxi** [beecloud/beecloud-php#19]
“在需要使用的php文件中使用 Composer 的 autoload 引入”这句话中的php文件指的是demo里面的php文件么？

**Comment by Danzeer** [comment]
php 文件指的是 你实现逻辑的”php文件“中

如果使用composer包管理你的php依赖，在文件头加上
include_once(<path>/vender/autoload.php); composer就会根据使用的类去自动加载文件了
