### ISSUE TITLE
有打算支持 psr-4 标准么？

### ISSUE THREAD

**Issue by JellyBool** [beecloud/beecloud-php#32]
看了一下源码，是出于什么原因考虑，本代码没有按照 psr-4 的标准和规范来？

**Comment by jasonhzy** [comment]
为了兼容之前老用户，针对PHP PSR标准，目录结构没有做出调整，所以目前并不是太严格遵守，在之后的升级中我们会相应的考虑，谢谢您提出的宝贵意见
