### ISSUE TITLE
Master_Secret和Test_Secret在不同场景中的应用疑问

### ISSUE THREAD

**Issue by bravist** [beecloud/beecloud-php#46]
> 客户需要在服务端依据规则要验证数字签名是否正确，购买的产品与订单金额是否匹配，这两个验证缺一不可

支付的时候只需要验证上面的三个逻辑，但是在退款的时候会需要填写Master_Secret和Test_Secret。

`BeecloudRefund::registerApp($this->appId, $this->appSecret, $this->masterSecret, $this->testSecret);
            $res = BeecloudRefund::refund($data);`

请问是什么原因必须要验证这两个Secret

**Comment by jasonhzy** [comment]
test secret 是为测试时使用的，退款不使用，退款时采用的是mster secret,采用不同的secret是为了安全考虑的
